baseURL = "https://quan-nh.github.io/notes/"
canonifyURLs = true
languageCode = "en-us"
title = "q-notes"
theme = "smol"
publishDir = "docs"
# Parameters
[params]
    subtitle = "Note all the things!"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

#   [[menu.main]]
#         identifier = "categories"
#         name = "Categories"
#         url = "/categories/"
#         weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/quan-nh"
        weight = 1 

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/huu2uan"
        weight = 2 

    [[menu.footer]]
        name = "RSS"
        url = "/index.xml"
        weight = 3

[permalinks]
  posts = "/:year/:month/:title/"
